apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: nginx-ingress-controller
requires:
  - path: ./skaffold.cert-manager.yaml
deploy:
  helm:
    releases:
      - name: nginx-ingress-controller
        repo: https://charts.bitnami.com/bitnami
        remoteChart: nginx-ingress-controller
        version: 9.9.5
        valuesFiles: [ spec/nginx-ingress-controller/values.yaml ]
