apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: infrastructure
deploy:
  helm:
    releases:
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        version: v1.13.3
        valuesFiles: [ spec/cert-manager/values.yaml ]
      - name: cert-manager-cluster-issuer
        chartPath: spec/charts/cert-manager-cluster-issuer
      - name: nginx-ingress-controller
        repo: https://charts.bitnami.com/bitnami
        remoteChart: nginx-ingress-controller
        version: 9.9.5
        valuesFiles: [ spec/nginx-ingress-controller/values.yaml ]
      - name: mailhog
        repo: https://codecentric.github.io/helm-charts
        remoteChart: mailhog
        version: 5.2.3
        valuesFiles: [ spec/mailhog/values.yaml ]
