apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: infrastructure
deploy:
  helm:
    releases:
      - name: mailhog
        repo: https://codecentric.github.io/helm-charts
        remoteChart: mailhog
        version: 5.8.0
        valuesFiles: [ values.yaml ]
