apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-cert
spec:
  dnsNames:
    - postgresql.default.svc.cluster.local
    - postgresql.default.svc
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  secretName: postgresql-cert
