apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: traefik
deploy:
  helm:
    releases:
      - name: postgres-operator
        repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
        remoteChart: postgres-operator
        version: 1.12.2
        valuesFiles: [ values.yaml ]
      - name: postgres-database
        chartPath: chart
        version: 0.0.1
