apiVersion: v2
name: prometheus-stack
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    alias: prometheus-stack
    version: 56.6.2
    repository: https://prometheus-community.github.io/helm-charts
