apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: percona-mongodb-server
deploy:
  helm:
    releases:
      - name: mongodb-server
        repo: https://percona.github.io/percona-helm-charts
        remoteChart: psmdb-db
        version: 1.18.0
        valuesFiles: [ values.yaml ]
