apiVersion: kdev.deranged.dk/v1
kind: Cluster
metadata:
  name: local-deranged-dk
spec:
  kind:
    version: "1.30"
  charts:
    - name: minio
      remoteChart: oci://registry-1.docker.io/bitnamicharts/minio
      version: 15.0.3
      values:
        auth:
          rootUser: root
          rootPassword: rootroot # must be at least 8 characters
        provisioning:
          enabled: true
          extraCommands:
            ## we do this to set anonymous access to the public bucket
            ## see https://github.com/bitnami/charts/issues/19523
            - mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
            - mc anonymous set download minio/public
          users:
            - username: write-only
              password: write-only
              policies:
                - writeonly
              setPolicies: true
            - username: read-only
              password: read-only
              policies:
                - writeonly
              setPolicies: true
          buckets:
            - name: public
