apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: mongodb-community-server
deploy:
  helm:
    releases:
      - name: ory-hydra-storage
        chartPath: chart
      - name: percona-mongodb-server
        repo: https://percona.github.io/percona-helm-charts
        remoteChart: psmdb-db
        version: 1.15.0
        valuesFiles: [ spec/percona-mongodb-server/values.yaml ]
