apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"

nodes:
- role: control-plane
  image: kindest/node:v1.30.8
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30080      # http
    listenAddress: 127.0.0.1
    hostPort: 80
    protocol: TCP
  - containerPort: 30443      # https
    listenAddress: 127.0.0.1
    hostPort: 443
    protocol: TCP
- role: worker
  image: kindest/node:v1.30.8
- role: worker
  image: kindest/node:v1.30.8

networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
